name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  image-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ianstigli/lambda:${{ github.sha }}

      - name: Docker Push
        run: docker push ianstigli/lambda:${{ github.sha }}