name: Dockerfile Review

on:
  push

jobs:
  is-dockerfiles-changed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: phpfile
            path: testfile.php
          - dockerfile: javafile
            path: testclass.java
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Filter Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          filters: |
            ${{matrix.dockerfile}}:
              - ${{matrix.path}}

      - name: Dump GitHub context
        if: steps.filter.outputs.changes != '[]'
        run: |
          echo ${{steps.filter.outputs.changes}}
          echo 'This file has been changed'