name: Dockerfile Review

on:
  push

env:
  phpfile: 'testfile.php'
  javafile: 'testclass.java'

jobs:
  is-dockerfiles-changed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [phpfile, javafile]
    outputs:
      phpfile: ${{ steps.filter.outputs.phpfile }}
      javafile: ${{ steps.filter.outputs.javafile }}
    env:
      DOCKERFILE_PATH: ${{ env[format('{0}_path', matrix.dockerfile)] }}
    steps:
      - name: Test
        run: echo ${{ matrix.dockerfile }}

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Filter Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          filters: |
            phpfile:
              - ${{ env.DOCKERFILE_PATH }}
            javafile:
              - ${{ env.DOCKERFILE_PATH }}

      - name: Set Outputs
        run: |
          echo "phpfile=${{ steps.filter.outputs.phpfile }}" >> $GITHUB_OUTPUT
          echo "javafile=${{ steps.filter.outputs.javafile }}" >> $GITHUB_OUTPUT