name: Dockerfile Review

on:
  push:
    branches:
      - main

jobs:
  dockerfile-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          dockerfile: "Dockerfile"