name: Dockerfile Review

on:
  push

env:
  phpfile_path: 'testfile.php'

  javafile_path: 'testclass.java'

jobs:
  is-dockerfiles-changed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [ phpfile, javafile]
    outputs:
      papapa: ${{ matrix.dockerfile )] }}
    env:
      value: ${{matrix.dockerfile}}
      dockerfile_path: ${{ env[format('env_{0}_path', value )] }}
    steps:
      - name: Test
        run: echo ${{env.value}}

      - name: Clone repository2
        uses: actions/checkout@v3

      - name: Filter Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          filters: |
            ${{matrix.dockerfile}}:
              - ${{env.dockerfile_path}}

      - name: Set Outputs
        run: |
          echo "papapa=${{ steps.filter.outputs[format('{0}', matrix.dockerfile )] }}" >> $GITHUB_OUTPUT
