name: Dockerfile Review

on: [pull_request]

env:
  phpfile: 'testfile.php'

  javafile: 'testclass.java'

jobs:
  is-dockerfiles-changed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [ phpfile, javafile]
    env:
      dockerfile_path: ${{ env[format('{0}_path', matrix.dockerfile )] }}
      matrix_reference: ${{matrix.dockerfile}}
    outputs:
      ${{matrix.dockerfile}}: ${{ steps.filter.outputs[format('{0}', matrix.dockerfile )] }}
    steps:
      - name: Test
        run: echo ${{ steps.filter.outputs[format('{0}', matrix.dockerfile )] }}

      - name: Clone repository2
        uses: actions/checkout@v3

      - name: Filter Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          filters: |
            ${{matrix.dockerfile}}:
              - ${{env.dockerfile_reference}}

      - name: Set Outputs
        run: |
          echo "${{matrix.dockerfile}}=${{ steps.filter.outputs[format('{0}', matrix.dockerfile )] }}" >> $GITHUB_OUTPUT
