name: Deploy to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1

jobs:
    lambda-images:
      needs: [ release-semantic-version ]
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build and tag images
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: lambda
          run: |
            docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:lambda-notification .
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:lambda-notification $ECR_REGISTRY/$ECR_REPOSITORY:lambda-notification:1.1.1
            
        - name: Push images to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: lambdas
          run: |
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:lambda-notification:1.1.1
